# Generated by Django 4.1.4 on 2022-12-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(unique=True)),
                ('cnic', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cnic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
