# Generated by Django 4.1 on 2022-12-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehicle_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='car_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='cnic',
            field=models.CharField(max_length=20),
        ),
    ]
