# Generated by Django 4.1.4 on 2022-12-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnicapi', '0002_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cars',
        ),
    ]
