# Generated by Django 4.1.4 on 2022-12-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnicapi', '0005_alter_vehicle_options_vehicle_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cnic',
            field=models.IntegerField(max_length=100),
        ),
    ]
