# Generated by Django 4.1.4 on 2022-12-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnicapi', '0016_rename_cnic_id_vehicle_cnic_alter_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
