# Generated by Django 4.1.4 on 2022-12-25 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cnicapi', '0018_rename_cnic_vehicle_cnic_id_alter_vehicle_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='cnic_id',
            new_name='cnic',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='car_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
