# Generated by Django 4.1.4 on 2022-12-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnicapi', '0019_rename_cnic_id_vehicle_cnic_vehicle_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cnic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cnicapi.person'),
        ),
    ]
