# Generated by Django 4.1.4 on 2022-12-25 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cnicapi', '0021_alter_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.IntegerField(default=django.utils.timezone.now, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='cnic',
            field=models.IntegerField(unique=True),
        ),
    ]
